"""rename_name_field_in_post

Revision ID: b3248981fdc2
Revises: afab8cf27ca2
Create Date: 2026-08-22 17:32:12.175431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3248981fdc2'
down_revision: Union[str, Sequence[str], None] = 'afab8cf27ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('posts', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
